# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.
name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest
    steps:
      - name: "'src' Depo Kontrolü"
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: "'build' Klasörü Oluştur"
        run: mkdir -p builds

      - name: Eski Derlemeleri Temizle
        run: rm -rf $GITHUB_WORKSPACE/builds/* || true

      - name: JDK 17 Ayarla
        uses: actions/setup-java@v4.6.0
        with:
          distribution: adopt
          java-version: 17

      - name: Android SDK Ayarla
        uses: android-actions/setup-android@v3.2.2

      - name: Eklentileri Derle
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Yeni Repository Oluştur ve Pushla
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/builds
          git init
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git branch -m builds
          git add .
          git commit -m "$GITHUB_SHA 'nın Derlenmesi"
          git remote add origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git
          git push -u origin builds --force
